# Generated by Django 2.2.16 on 2022-11-20 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221121_0118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'default_related_name': 'posts', 'ordering': ('created',), 'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
    ]
